### ISSUE TITLE
Rolling shutter camera with radial distortion?

### ISSUE THREAD

**Issue by hemangchawla** [IRVLab/unrolling#1]
Hi,
I would like to know 
1. If you have tested on datasets with radial distortion captured with rolling shutter effect?
2. Does it preserve the radial distortion upon unrolling?
3. Does the presence or absence of radial distortion affect the accuracy of unrolling?
Thank you

**Comment by jiawei-mo** [comment]
Hi,

Thanks for your interest in this project.

We remove the lens distortion when processing the dataset, so the network works on undistorted input/output. We briefly talked about this in the [paper](https://arxiv.org/pdf/2011.03106.pdf).
Lens distortion is taken care of when generating the (undistorted) RS/GS image pairs for training the network. Specifically, we undistort the images and maintain a [loop-up table](https://github.com/IRVLab/unrolling/blob/d28185f1a4800d16fc3e326638ffe34da4aeb3aa/tum_process/stereoRectifier.py#L65) from the undistorted pixel coordinate to the original pixel coordinate. To recover the depth, we use the relative pose at the [original pixel coordinate](https://github.com/IRVLab/unrolling/blob/d28185f1a4800d16fc3e326638ffe34da4aeb3aa/tum_process/depthEstimator.py#L88). Similar for [projecting RS pixel to GS frame](https://github.com/IRVLab/unrolling/blob/d28185f1a4800d16fc3e326638ffe34da4aeb3aa/tum_process/gtFlowGenerator.py#L51).  After the dataset process, all images are without lens distortions.

In order to preserve the distortion, we can manually distort the output using the distortion parameters.

Let me know if you have further questions.

Best,
Jiawei
